local_costmap:

  #Set the global and robot frames for the costmap
  global_frame: map
  robot_base_frame: base_link
   
  #We'll configure this costmap to be a rolling window... meaning it is always centered at the robot
  static_map: false
  rolling_window: true
  width: 4.0
  height: 4.0
  resolution: 0.05

  transform_tolerance: 13.5
  plugins:
    - {name: static_layer,        type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer,      type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer,     type: "costmap_2d::InflationLayer"}
